// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internalrpc/img_sync.proto

package internalrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DgeTokenRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *DgeTokenRequest) Reset()                    { *m = DgeTokenRequest{} }
func (m *DgeTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*DgeTokenRequest) ProtoMessage()               {}
func (*DgeTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *DgeTokenRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type DgeTokenResponse struct {
	Auth       string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Timestamp  int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	OperatorId uint32 `protobuf:"varint,3,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
	ImgId      string `protobuf:"bytes,4,opt,name=img_id,json=imgId" json:"img_id,omitempty"`
}

func (m *DgeTokenResponse) Reset()                    { *m = DgeTokenResponse{} }
func (m *DgeTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*DgeTokenResponse) ProtoMessage()               {}
func (*DgeTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *DgeTokenResponse) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *DgeTokenResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DgeTokenResponse) GetOperatorId() uint32 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *DgeTokenResponse) GetImgId() string {
	if m != nil {
		return m.ImgId
	}
	return ""
}

func init() {
	proto.RegisterType((*DgeTokenRequest)(nil), "internalrpc.DgeTokenRequest")
	proto.RegisterType((*DgeTokenResponse)(nil), "internalrpc.DgeTokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ImgSync service

type ImgSyncClient interface {
	GetDgeToken(ctx context.Context, in *DgeTokenRequest, opts ...grpc.CallOption) (*DgeTokenResponse, error)
	HealthCheck(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type imgSyncClient struct {
	cc *grpc.ClientConn
}

func NewImgSyncClient(cc *grpc.ClientConn) ImgSyncClient {
	return &imgSyncClient{cc}
}

func (c *imgSyncClient) GetDgeToken(ctx context.Context, in *DgeTokenRequest, opts ...grpc.CallOption) (*DgeTokenResponse, error) {
	out := new(DgeTokenResponse)
	err := grpc.Invoke(ctx, "/internalrpc.ImgSync/GetDgeToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncClient) HealthCheck(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/internalrpc.ImgSync/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImgSync service

type ImgSyncServer interface {
	GetDgeToken(context.Context, *DgeTokenRequest) (*DgeTokenResponse, error)
	HealthCheck(context.Context, *google_protobuf1.Empty) (*HealthCheckResponse, error)
}

func RegisterImgSyncServer(s *grpc.Server, srv ImgSyncServer) {
	s.RegisterService(&_ImgSync_serviceDesc, srv)
}

func _ImgSync_GetDgeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DgeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncServer).GetDgeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalrpc.ImgSync/GetDgeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncServer).GetDgeToken(ctx, req.(*DgeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSync_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalrpc.ImgSync/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncServer).HealthCheck(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImgSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internalrpc.ImgSync",
	HandlerType: (*ImgSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDgeToken",
			Handler:    _ImgSync_GetDgeToken_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ImgSync_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalrpc/img_sync.proto",
}

func init() { proto.RegisterFile("internalrpc/img_sync.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xff, 0xb4, 0xfd, 0x8b, 0x3a, 0x11, 0x17, 0x59, 0x02, 0x85, 0xb4, 0x15, 0xa1, 0xab,
	0xae, 0x5c, 0x09, 0xde, 0x80, 0x8b, 0x20, 0x12, 0xab, 0xc0, 0xbe, 0x72, 0x92, 0xc1, 0xb5, 0x1a,
	0x5f, 0xb0, 0xdd, 0x45, 0x25, 0x9e, 0x86, 0x27, 0x45, 0x4d, 0x1b, 0x25, 0x20, 0xb1, 0xb3, 0xe7,
	0x9c, 0x39, 0x9a, 0xef, 0x40, 0x2c, 0x94, 0x47, 0xab, 0x58, 0x65, 0x4d, 0xb1, 0x10, 0x92, 0x2f,
	0xdd, 0x56, 0x15, 0xd4, 0x58, 0xed, 0x35, 0x09, 0x3b, 0x5a, 0x7c, 0xd9, 0x35, 0x72, 0x54, 0x68,
	0xc5, 0xc1, 0x17, 0x8f, 0xb9, 0xd6, 0xbc, 0xc2, 0x45, 0xfd, 0xcb, 0x37, 0xef, 0x0b, 0x94, 0xc6,
	0x6f, 0xf7, 0xe2, 0xec, 0x1a, 0x4e, 0x1f, 0x38, 0xbe, 0xe9, 0x35, 0xaa, 0x0c, 0x3f, 0x36, 0xe8,
	0x3c, 0x39, 0x81, 0x9e, 0x30, 0x51, 0x90, 0x04, 0xf3, 0x51, 0xd6, 0x13, 0x66, 0xf6, 0x09, 0x67,
	0xad, 0xc5, 0x19, 0xad, 0x1c, 0x12, 0x02, 0x03, 0xb6, 0xf1, 0xab, 0x83, 0xab, 0x7e, 0x93, 0x09,
	0x8c, 0xbc, 0x90, 0xe8, 0x3c, 0x93, 0x26, 0xea, 0x25, 0xc1, 0xbc, 0x9f, 0xb5, 0x03, 0x72, 0x05,
	0xa1, 0x36, 0x68, 0x99, 0xd7, 0x76, 0x29, 0xca, 0xa8, 0x9f, 0x04, 0xf3, 0xe3, 0x0c, 0x9a, 0x51,
	0x5a, 0x92, 0x73, 0x18, 0xee, 0x00, 0x45, 0x19, 0x0d, 0xea, 0xd0, 0xff, 0x42, 0xf2, 0xb4, 0xbc,
	0xf9, 0x0a, 0xe0, 0x28, 0x95, 0xfc, 0x75, 0xab, 0x0a, 0xf2, 0x02, 0xe1, 0x13, 0xfa, 0xe6, 0x18,
	0x32, 0xa1, 0x1d, 0x68, 0xfa, 0x0b, 0x23, 0x9e, 0xfe, 0xa1, 0xee, 0x09, 0x66, 0xff, 0x48, 0x0a,
	0xe1, 0x33, 0xb2, 0xca, 0xaf, 0xee, 0x57, 0x58, 0xac, 0xc9, 0x05, 0xdd, 0xf7, 0x44, 0x9b, 0x9e,
	0xe8, 0xe3, 0xae, 0xa7, 0x38, 0xf9, 0x91, 0xd3, 0xd9, 0x68, 0xa3, 0xee, 0xa6, 0x30, 0x2e, 0xb4,
	0xa4, 0xb9, 0xf0, 0x9c, 0x49, 0xac, 0x58, 0xee, 0xba, 0x4b, 0xf9, 0xb0, 0x8e, 0xbc, 0xfd, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x35, 0x06, 0xf1, 0xf0, 0xce, 0x01, 0x00, 0x00,
}
