// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchangerates/bitcoinfees.proto

/*
Package exchangerates is a generated protocol buffer package.

It is generated from these files:
	exchangerates/bitcoinfees.proto
	exchangerates/exchangerates.proto

It has these top-level messages:
	BitcoinFees
	CurrencyPair
	API
*/
package exchangerates

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BitcoinFees struct {
	Fastest          *float64 `protobuf:"fixed64,1,opt,name=fastest" json:"fastest,omitempty"`
	HalfHour         *float64 `protobuf:"fixed64,2,opt,name=half_hour,json=halfHour" json:"half_hour,omitempty"`
	Hour             *float64 `protobuf:"fixed64,3,opt,name=hour" json:"hour,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BitcoinFees) Reset()                    { *m = BitcoinFees{} }
func (m *BitcoinFees) String() string            { return proto.CompactTextString(m) }
func (*BitcoinFees) ProtoMessage()               {}
func (*BitcoinFees) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BitcoinFees) GetFastest() float64 {
	if m != nil && m.Fastest != nil {
		return *m.Fastest
	}
	return 0
}

func (m *BitcoinFees) GetHalfHour() float64 {
	if m != nil && m.HalfHour != nil {
		return *m.HalfHour
	}
	return 0
}

func (m *BitcoinFees) GetHour() float64 {
	if m != nil && m.Hour != nil {
		return *m.Hour
	}
	return 0
}

func init() {
	proto.RegisterType((*BitcoinFees)(nil), "exchangerates.BitcoinFees")
}

func init() { proto.RegisterFile("exchangerates/bitcoinfees.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xad, 0x48, 0xce,
	0x48, 0xcc, 0x4b, 0x4f, 0x2d, 0x4a, 0x2c, 0x49, 0x2d, 0xd6, 0x4f, 0xca, 0x2c, 0x49, 0xce, 0xcf,
	0xcc, 0x4b, 0x4b, 0x4d, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x51, 0xa0,
	0x14, 0xc1, 0xc5, 0xed, 0x04, 0x51, 0xe3, 0x96, 0x9a, 0x5a, 0x2c, 0x24, 0xc1, 0xc5, 0x9e, 0x96,
	0x58, 0x5c, 0x92, 0x5a, 0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x18, 0x04, 0xe3, 0x0a, 0x49,
	0x73, 0x71, 0x66, 0x24, 0xe6, 0xa4, 0xc5, 0x67, 0xe4, 0x97, 0x16, 0x49, 0x30, 0x81, 0xe5, 0x38,
	0x40, 0x02, 0x1e, 0xf9, 0xa5, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0x60, 0x71, 0x66, 0xb0, 0x38, 0x98,
	0xed, 0x24, 0xcf, 0x25, 0x9b, 0x9c, 0x9f, 0xab, 0x97, 0x94, 0x59, 0x92, 0x9e, 0x98, 0x9b, 0x9a,
	0x93, 0x98, 0x54, 0xac, 0x87, 0x62, 0x35, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x2b, 0xbf, 0x37,
	0xab, 0x00, 0x00, 0x00,
}
