// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// isExtraField_Value is an autogenerated mock type for the isExtraField_Value type
type isExtraField_Value struct {
	mock.Mock
}

// isExtraField_Value provides a mock function with given fields:
func (_m *isExtraField_Value) isExtraField_Value() {
	_m.Called()
}
