// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// isRemoveBettingOverlayRequest_OverlayLookup is an autogenerated mock type for the isRemoveBettingOverlayRequest_OverlayLookup type
type isRemoveBettingOverlayRequest_OverlayLookup struct {
	mock.Mock
}

// isRemoveBettingOverlayRequest_OverlayLookup provides a mock function with given fields:
func (_m *isRemoveBettingOverlayRequest_OverlayLookup) isRemoveBettingOverlayRequest_OverlayLookup() {
	_m.Called()
}
