// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "golang.org/x/net/context"
import internalrpc "github.com/bitgaming/go-protobuf-schema/internalrpc"
import mock "github.com/stretchr/testify/mock"

// PinnacleBrokerServer is an autogenerated mock type for the PinnacleBrokerServer type
type PinnacleBrokerServer struct {
	mock.Mock
}

// FetchLine provides a mock function with given fields: _a0, _a1
func (_m *PinnacleBrokerServer) FetchLine(_a0 context.Context, _a1 *internalrpc.Line) (*internalrpc.Line, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *internalrpc.Line
	if rf, ok := ret.Get(0).(func(context.Context, *internalrpc.Line) *internalrpc.Line); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalrpc.Line)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *internalrpc.Line) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMaxStakeFor provides a mock function with given fields: _a0, _a1
func (_m *PinnacleBrokerServer) GetMaxStakeFor(_a0 context.Context, _a1 *internalrpc.Selection) (*internalrpc.Double, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *internalrpc.Double
	if rf, ok := ret.Get(0).(func(context.Context, *internalrpc.Selection) *internalrpc.Double); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalrpc.Double)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *internalrpc.Selection) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
