// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payments/crypto-payments.proto

/*
Package payments is a generated protocol buffer package.

It is generated from these files:
	payments/crypto-payments.proto
	payments/deposit.proto
	payments/withdrawal.proto

It has these top-level messages:
	CheckAddressesRequest
	CheckAddressesReply
	TransactionInput
	TransactionOutput
	HandleTransactionRequest
	Deposit
	Withdrawal
*/
package payments

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckAddressesRequest struct {
	Currency  string   `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *CheckAddressesRequest) Reset()                    { *m = CheckAddressesRequest{} }
func (m *CheckAddressesRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckAddressesRequest) ProtoMessage()               {}
func (*CheckAddressesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckAddressesRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CheckAddressesRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CheckAddressesReply struct {
	AddressFound bool `protobuf:"varint,1,opt,name=address_found,json=addressFound" json:"address_found,omitempty"`
}

func (m *CheckAddressesReply) Reset()                    { *m = CheckAddressesReply{} }
func (m *CheckAddressesReply) String() string            { return proto.CompactTextString(m) }
func (*CheckAddressesReply) ProtoMessage()               {}
func (*CheckAddressesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckAddressesReply) GetAddressFound() bool {
	if m != nil {
		return m.AddressFound
	}
	return false
}

type TransactionInput struct {
	Index int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Hash  string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *TransactionInput) Reset()                    { *m = TransactionInput{} }
func (m *TransactionInput) String() string            { return proto.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()               {}
func (*TransactionInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransactionInput) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionInput) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type TransactionOutput struct {
	Index   int32   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Value   float64 `protobuf:"fixed64,3,opt,name=value" json:"value,omitempty"`
}

func (m *TransactionOutput) Reset()                    { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string            { return proto.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()               {}
func (*TransactionOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionOutput) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TransactionOutput) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type HandleTransactionRequest struct {
	Currency             string               `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
	BlockchainSeenAt     int32                `protobuf:"varint,2,opt,name=blockchain_seen_at,json=blockchainSeenAt" json:"blockchain_seen_at,omitempty"`
	ConfirmedBlockHash   string               `protobuf:"bytes,3,opt,name=confirmed_block_hash,json=confirmedBlockHash" json:"confirmed_block_hash,omitempty"`
	ConfirmedBlockHeight int32                `protobuf:"varint,4,opt,name=confirmed_block_height,json=confirmedBlockHeight" json:"confirmed_block_height,omitempty"`
	Fee                  float64              `protobuf:"fixed64,5,opt,name=fee" json:"fee,omitempty"`
	Inputs               []*TransactionInput  `protobuf:"bytes,6,rep,name=inputs" json:"inputs,omitempty"`
	Outputs              []*TransactionOutput `protobuf:"bytes,7,rep,name=outputs" json:"outputs,omitempty"`
	Size                 float64              `protobuf:"fixed64,8,opt,name=size" json:"size,omitempty"`
	TransactionHash      string               `protobuf:"bytes,9,opt,name=transaction_hash,json=transactionHash" json:"transaction_hash,omitempty"`
}

func (m *HandleTransactionRequest) Reset()                    { *m = HandleTransactionRequest{} }
func (m *HandleTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleTransactionRequest) ProtoMessage()               {}
func (*HandleTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HandleTransactionRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *HandleTransactionRequest) GetBlockchainSeenAt() int32 {
	if m != nil {
		return m.BlockchainSeenAt
	}
	return 0
}

func (m *HandleTransactionRequest) GetConfirmedBlockHash() string {
	if m != nil {
		return m.ConfirmedBlockHash
	}
	return ""
}

func (m *HandleTransactionRequest) GetConfirmedBlockHeight() int32 {
	if m != nil {
		return m.ConfirmedBlockHeight
	}
	return 0
}

func (m *HandleTransactionRequest) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *HandleTransactionRequest) GetInputs() []*TransactionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *HandleTransactionRequest) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *HandleTransactionRequest) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *HandleTransactionRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckAddressesRequest)(nil), "payments.CheckAddressesRequest")
	proto.RegisterType((*CheckAddressesReply)(nil), "payments.CheckAddressesReply")
	proto.RegisterType((*TransactionInput)(nil), "payments.TransactionInput")
	proto.RegisterType((*TransactionOutput)(nil), "payments.TransactionOutput")
	proto.RegisterType((*HandleTransactionRequest)(nil), "payments.HandleTransactionRequest")
}

func init() { proto.RegisterFile("payments/crypto-payments.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0xea, 0xe6, 0x6b, 0x80, 0x92, 0x2e, 0xa1, 0x5a, 0xb9, 0x7c, 0x44, 0xe6, 0x12, 0x24,
	0x70, 0x50, 0x80, 0x0b, 0xe2, 0xd2, 0x56, 0xa0, 0x72, 0x82, 0x2e, 0x5c, 0x38, 0x45, 0x6b, 0x7b,
	0x12, 0x5b, 0xb5, 0x77, 0x8d, 0x77, 0x8d, 0x30, 0xbf, 0x80, 0x7f, 0xc4, 0xdf, 0x43, 0x5e, 0xdb,
	0x71, 0x48, 0x1b, 0xa9, 0xb7, 0x7d, 0x33, 0xef, 0xcd, 0xdb, 0xd9, 0x99, 0x85, 0x27, 0x29, 0x2f,
	0x12, 0x14, 0x5a, 0xcd, 0xfc, 0xac, 0x48, 0xb5, 0x7c, 0xd9, 0x60, 0x37, 0xcd, 0xa4, 0x96, 0x64,
	0xd0, 0x60, 0xfb, 0x64, 0x25, 0xe5, 0x2a, 0xc6, 0x99, 0x89, 0x7b, 0xf9, 0x72, 0x86, 0x49, 0xaa,
	0x8b, 0x8a, 0xe6, 0x5c, 0xc2, 0xc3, 0xf3, 0x10, 0xfd, 0xab, 0xd3, 0x20, 0xc8, 0x50, 0x29, 0x54,
	0x0c, 0x7f, 0xe4, 0xa8, 0x34, 0xb1, 0x61, 0xe0, 0xe7, 0x59, 0x86, 0xc2, 0x2f, 0x68, 0x67, 0xd2,
	0x99, 0x0e, 0xd9, 0x1a, 0x93, 0x47, 0x30, 0xe4, 0x0d, 0x9f, 0xee, 0x4f, 0xac, 0xe9, 0x90, 0xb5,
	0x01, 0xe7, 0x1d, 0x3c, 0xd8, 0x2e, 0x99, 0xc6, 0x05, 0x79, 0x06, 0xf7, 0x6a, 0xce, 0x62, 0x29,
	0x73, 0x11, 0x98, 0xaa, 0x03, 0x76, 0xb7, 0x0e, 0x7e, 0x2c, 0x63, 0xce, 0x7b, 0x18, 0x7d, 0xcb,
	0xb8, 0x50, 0xdc, 0xd7, 0x91, 0x14, 0x9f, 0x44, 0x9a, 0x6b, 0x32, 0x86, 0x6e, 0x24, 0x02, 0xfc,
	0x65, 0x04, 0x5d, 0x56, 0x01, 0x42, 0xe0, 0x20, 0xe4, 0x2a, 0xa4, 0xfb, 0xe6, 0x6e, 0xe6, 0xec,
	0x7c, 0x87, 0xa3, 0x0d, 0xf5, 0xe7, 0x5c, 0xef, 0x96, 0x53, 0xe8, 0xd7, 0xc6, 0x75, 0x85, 0x06,
	0x96, 0xfc, 0x9f, 0x3c, 0xce, 0x91, 0x5a, 0x93, 0xce, 0xb4, 0xc3, 0x2a, 0xe0, 0xfc, 0xb1, 0x80,
	0x5e, 0x70, 0x11, 0xc4, 0xb8, 0xe1, 0x70, 0x9b, 0xb7, 0x7a, 0x01, 0xc4, 0x8b, 0xa5, 0x7f, 0xe5,
	0x87, 0x3c, 0x12, 0x0b, 0x85, 0x28, 0x16, 0x5c, 0x1b, 0xcf, 0x2e, 0x1b, 0xb5, 0x99, 0xaf, 0x88,
	0xe2, 0x54, 0x93, 0x57, 0x30, 0xf6, 0xa5, 0x58, 0x46, 0x59, 0x82, 0xc1, 0xc2, 0x64, 0x17, 0xa6,
	0x4b, 0xcb, 0x54, 0x25, 0xeb, 0xdc, 0x59, 0x99, 0xba, 0xe0, 0x2a, 0x24, 0x6f, 0xe0, 0xf8, 0x9a,
	0x02, 0xa3, 0x55, 0xa8, 0xe9, 0x81, 0xf1, 0x18, 0x6f, 0x69, 0x4c, 0x8e, 0x8c, 0xc0, 0x5a, 0x22,
	0xd2, 0xae, 0x69, 0xb1, 0x3c, 0x92, 0x39, 0xf4, 0xa2, 0xf2, 0xb9, 0x15, 0xed, 0x4d, 0xac, 0xe9,
	0x9d, 0xb9, 0xed, 0xae, 0x17, 0x6a, 0x7b, 0x22, 0xac, 0x66, 0x92, 0xb7, 0xd0, 0x97, 0xe6, 0x91,
	0x15, 0xed, 0x1b, 0xd1, 0xc9, 0x8d, 0xa2, 0x6a, 0x10, 0xac, 0xe1, 0x96, 0xa3, 0x53, 0xd1, 0x6f,
	0xa4, 0x03, 0xe3, 0x6e, 0xce, 0xe4, 0x39, 0x8c, 0x74, 0xab, 0xa8, 0x9a, 0x1e, 0x9a, 0xa6, 0xef,
	0x6f, 0xc4, 0xcb, 0x8e, 0xe7, 0x7f, 0x3b, 0x70, 0x78, 0x6e, 0x76, 0xfe, 0x4b, 0x6d, 0x46, 0x18,
	0x1c, 0xfe, 0xbf, 0x72, 0xe4, 0x69, 0x7b, 0x93, 0x1b, 0xf7, 0xdb, 0x7e, 0xbc, 0x9b, 0x90, 0xc6,
	0x85, 0xb3, 0x47, 0x2e, 0xe1, 0xe8, 0xda, 0xc0, 0x89, 0xd3, 0xaa, 0x76, 0x6d, 0x83, 0x7d, 0xec,
	0x56, 0x1f, 0xce, 0x6d, 0x3e, 0x9c, 0xfb, 0xa1, 0xfc, 0x70, 0xce, 0xde, 0x99, 0x0d, 0xd4, 0x97,
	0x89, 0xeb, 0x45, 0x7a, 0xc5, 0x13, 0x8c, 0xb9, 0xa7, 0xd6, 0xe5, 0xbc, 0x9e, 0x61, 0xbf, 0xfe,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x78, 0x9f, 0x32, 0x92, 0xd8, 0x03, 0x00, 0x00,
}
