// Code generated by protoc-gen-go. DO NOT EDIT.
// source: casino/casino.proto

/*
Package casino is a generated protocol buffer package.

It is generated from these files:
	casino/casino.proto

It has these top-level messages:
	Bet
*/
package casino

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bet struct {
	Timestamp        *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Uuid             *string  `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	PlayerId         *uint32  `protobuf:"varint,3,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ClientId         *uint32  `protobuf:"varint,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Stake            *float64 `protobuf:"fixed64,5,opt,name=stake" json:"stake,omitempty"`
	GameId           *uint32  `protobuf:"varint,6,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	GameName         *string  `protobuf:"bytes,7,opt,name=game_name,json=gameName" json:"game_name,omitempty"`
	GameType         *string  `protobuf:"bytes,8,opt,name=game_type,json=gameType" json:"game_type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Bet) Reset()                    { *m = Bet{} }
func (m *Bet) String() string            { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()               {}
func (*Bet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bet) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Bet) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Bet) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Bet) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *Bet) GetStake() float64 {
	if m != nil && m.Stake != nil {
		return *m.Stake
	}
	return 0
}

func (m *Bet) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *Bet) GetGameName() string {
	if m != nil && m.GameName != nil {
		return *m.GameName
	}
	return ""
}

func (m *Bet) GetGameType() string {
	if m != nil && m.GameType != nil {
		return *m.GameType
	}
	return ""
}

func init() {
	proto.RegisterType((*Bet)(nil), "casino.Bet")
}

func init() { proto.RegisterFile("casino/casino.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0xd2, 0xa6, 0xc9, 0x49, 0x2c, 0x06, 0x81, 0x25, 0x18, 0x22, 0x26, 0x4f, 0xe1,
	0x1d, 0xba, 0x75, 0x61, 0xb0, 0xd8, 0xd1, 0x35, 0x39, 0x21, 0x8b, 0x38, 0xb6, 0xea, 0xeb, 0x90,
	0x57, 0xe5, 0x69, 0x90, 0x7d, 0x12, 0x9d, 0xec, 0xff, 0xfb, 0xf4, 0x9f, 0xee, 0xe0, 0x61, 0xc2,
	0xec, 0xd7, 0xf8, 0x2e, 0xcf, 0x98, 0x2e, 0x91, 0xa3, 0x6e, 0x25, 0xbd, 0xfd, 0x2a, 0x68, 0x8e,
	0xc4, 0xfa, 0x15, 0x7a, 0xf6, 0x81, 0x32, 0x63, 0x48, 0x46, 0x0d, 0xca, 0x36, 0xee, 0x06, 0xb4,
	0x86, 0xdd, 0xf5, 0xea, 0x67, 0x73, 0x37, 0x28, 0xdb, 0xbb, 0xfa, 0xd7, 0x2f, 0xd0, 0xa7, 0x05,
	0x37, 0xba, 0x7c, 0xf9, 0xd9, 0x34, 0x83, 0xb2, 0xf7, 0xae, 0x13, 0x70, 0xaa, 0x72, 0x5a, 0x3c,
	0xad, 0x5c, 0xe4, 0x4e, 0xa4, 0x80, 0xd3, 0xac, 0x1f, 0x61, 0x9f, 0x19, 0x7f, 0xc8, 0xec, 0x07,
	0x65, 0x95, 0x93, 0xa0, 0x9f, 0xe1, 0xf0, 0x8d, 0x81, 0x4a, 0xa1, 0xad, 0x85, 0xb6, 0x44, 0x99,
	0x55, 0xc5, 0x8a, 0x81, 0xcc, 0xa1, 0x6e, 0xd0, 0x15, 0xf0, 0x81, 0x81, 0xfe, 0x25, 0x6f, 0x89,
	0x4c, 0x77, 0x93, 0x9f, 0x5b, 0xa2, 0xa3, 0x81, 0xa7, 0x29, 0x86, 0xf1, 0xec, 0xb9, 0xa0, 0x05,
	0xcf, 0x79, 0x94, 0xb3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x32, 0x44, 0x37, 0x14, 0x01,
	0x00, 0x00,
}
