// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitoring/monitoring.proto

/*
Package monitoring is a generated protocol buffer package.

It is generated from these files:
	monitoring/monitoring.proto

It has these top-level messages:
	ScoutIntMetric
	ScoutDecimalMetric
	ScoutStringMetric
	ScoutReport
*/
package monitoring

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScoutIntMetric struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	ScoutType        *string `protobuf:"bytes,3,opt,name=scout_type,json=scoutType" json:"scout_type,omitempty"`
	ScoutTimeframe   *string `protobuf:"bytes,4,opt,name=scout_timeframe,json=scoutTimeframe" json:"scout_timeframe,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ScoutIntMetric) Reset()                    { *m = ScoutIntMetric{} }
func (m *ScoutIntMetric) String() string            { return proto.CompactTextString(m) }
func (*ScoutIntMetric) ProtoMessage()               {}
func (*ScoutIntMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ScoutIntMetric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ScoutIntMetric) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ScoutIntMetric) GetScoutType() string {
	if m != nil && m.ScoutType != nil {
		return *m.ScoutType
	}
	return ""
}

func (m *ScoutIntMetric) GetScoutTimeframe() string {
	if m != nil && m.ScoutTimeframe != nil {
		return *m.ScoutTimeframe
	}
	return ""
}

type ScoutDecimalMetric struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	ScoutType        *string  `protobuf:"bytes,3,opt,name=scout_type,json=scoutType" json:"scout_type,omitempty"`
	ScoutTimeframe   *string  `protobuf:"bytes,4,opt,name=scout_timeframe,json=scoutTimeframe" json:"scout_timeframe,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ScoutDecimalMetric) Reset()                    { *m = ScoutDecimalMetric{} }
func (m *ScoutDecimalMetric) String() string            { return proto.CompactTextString(m) }
func (*ScoutDecimalMetric) ProtoMessage()               {}
func (*ScoutDecimalMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScoutDecimalMetric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ScoutDecimalMetric) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ScoutDecimalMetric) GetScoutType() string {
	if m != nil && m.ScoutType != nil {
		return *m.ScoutType
	}
	return ""
}

func (m *ScoutDecimalMetric) GetScoutTimeframe() string {
	if m != nil && m.ScoutTimeframe != nil {
		return *m.ScoutTimeframe
	}
	return ""
}

type ScoutStringMetric struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	ScoutType        *string `protobuf:"bytes,3,opt,name=scout_type,json=scoutType" json:"scout_type,omitempty"`
	ScoutTimeframe   *string `protobuf:"bytes,4,opt,name=scout_timeframe,json=scoutTimeframe" json:"scout_timeframe,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ScoutStringMetric) Reset()                    { *m = ScoutStringMetric{} }
func (m *ScoutStringMetric) String() string            { return proto.CompactTextString(m) }
func (*ScoutStringMetric) ProtoMessage()               {}
func (*ScoutStringMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ScoutStringMetric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ScoutStringMetric) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *ScoutStringMetric) GetScoutType() string {
	if m != nil && m.ScoutType != nil {
		return *m.ScoutType
	}
	return ""
}

func (m *ScoutStringMetric) GetScoutTimeframe() string {
	if m != nil && m.ScoutTimeframe != nil {
		return *m.ScoutTimeframe
	}
	return ""
}

type ScoutReport struct {
	IntMetrics       []*ScoutIntMetric     `protobuf:"bytes,1,rep,name=int_metrics,json=intMetrics" json:"int_metrics,omitempty"`
	DecimalMetrics   []*ScoutDecimalMetric `protobuf:"bytes,2,rep,name=decimal_metrics,json=decimalMetrics" json:"decimal_metrics,omitempty"`
	StringMetrics    []*ScoutStringMetric  `protobuf:"bytes,3,rep,name=string_metrics,json=stringMetrics" json:"string_metrics,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ScoutReport) Reset()                    { *m = ScoutReport{} }
func (m *ScoutReport) String() string            { return proto.CompactTextString(m) }
func (*ScoutReport) ProtoMessage()               {}
func (*ScoutReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ScoutReport) GetIntMetrics() []*ScoutIntMetric {
	if m != nil {
		return m.IntMetrics
	}
	return nil
}

func (m *ScoutReport) GetDecimalMetrics() []*ScoutDecimalMetric {
	if m != nil {
		return m.DecimalMetrics
	}
	return nil
}

func (m *ScoutReport) GetStringMetrics() []*ScoutStringMetric {
	if m != nil {
		return m.StringMetrics
	}
	return nil
}

func init() {
	proto.RegisterType((*ScoutIntMetric)(nil), "monitoring.ScoutIntMetric")
	proto.RegisterType((*ScoutDecimalMetric)(nil), "monitoring.ScoutDecimalMetric")
	proto.RegisterType((*ScoutStringMetric)(nil), "monitoring.ScoutStringMetric")
	proto.RegisterType((*ScoutReport)(nil), "monitoring.ScoutReport")
}

func init() { proto.RegisterFile("monitoring/monitoring.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xa6, 0x1e, 0x3a, 0xc1, 0x14, 0x07, 0x0f, 0xa1, 0x5a, 0x09, 0xbd, 0x98, 0x53,
	0x04, 0xaf, 0xde, 0xa4, 0x20, 0x1e, 0xbc, 0x6c, 0xbd, 0x97, 0x34, 0x5d, 0xcb, 0x42, 0x36, 0x1b,
	0xb2, 0x53, 0xa1, 0x57, 0x41, 0xdf, 0xd1, 0xb7, 0x91, 0x4c, 0x6c, 0xbb, 0xa5, 0x97, 0x1e, 0x7a,
	0x9b, 0x99, 0x9d, 0xfd, 0xf8, 0xf8, 0x07, 0x6e, 0x8c, 0xad, 0x34, 0xd9, 0x46, 0x57, 0xab, 0x87,
	0x7d, 0x99, 0xd5, 0x8d, 0x25, 0x8b, 0xb0, 0x9f, 0x4c, 0xbe, 0x04, 0x44, 0xb3, 0xc2, 0xae, 0xe9,
	0xb5, 0xa2, 0x37, 0x45, 0x8d, 0x2e, 0x10, 0xa1, 0x5f, 0xe5, 0x46, 0xc5, 0x22, 0x11, 0xe9, 0x40,
	0x72, 0x8d, 0xd7, 0x70, 0xf1, 0x99, 0x97, 0x6b, 0x15, 0xf7, 0x12, 0x91, 0x06, 0xb2, 0x6b, 0x70,
	0x0c, 0xe0, 0xda, 0xbf, 0x73, 0xda, 0xd4, 0x2a, 0x0e, 0x78, 0x7f, 0xc0, 0x93, 0xf7, 0x4d, 0xad,
	0xf0, 0x1e, 0x86, 0xff, 0xcf, 0xda, 0xa8, 0x8f, 0xa6, 0x65, 0xf6, 0x79, 0x27, 0xea, 0x76, 0xb6,
	0xd3, 0xc9, 0x8f, 0x00, 0x64, 0x89, 0xa9, 0x2a, 0xb4, 0xc9, 0xcb, 0x53, 0x45, 0xc4, 0xb9, 0x45,
	0xbe, 0x05, 0x5c, 0xb1, 0xc8, 0x8c, 0xda, 0x74, 0x4e, 0xf5, 0x18, 0x9c, 0xdb, 0xe3, 0x57, 0x40,
	0xc8, 0x1e, 0x52, 0xd5, 0xb6, 0x21, 0x7c, 0x82, 0x50, 0x57, 0x34, 0x37, 0xec, 0xe3, 0x62, 0x91,
	0x04, 0x69, 0xf8, 0x38, 0xca, 0xbc, 0xcb, 0x1e, 0xde, 0x50, 0x82, 0xde, 0x96, 0x0e, 0x5f, 0x60,
	0xb8, 0xec, 0x72, 0xdd, 0x01, 0x7a, 0x0c, 0xb8, 0x3b, 0x02, 0x1c, 0xe4, 0x2f, 0xa3, 0xa5, 0xdf,
	0x3a, 0x9c, 0x42, 0xe4, 0x38, 0x97, 0x1d, 0x27, 0x60, 0xce, 0xf8, 0x88, 0xe3, 0xc7, 0x27, 0x2f,
	0x9d, 0xd7, 0xb9, 0xe7, 0x5b, 0x18, 0x15, 0xd6, 0x64, 0x0b, 0x4d, 0xab, 0xdc, 0xa8, 0x32, 0x5f,
	0x38, 0xef, 0xfb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x20, 0x09, 0x61, 0xb9, 0x02, 0x00,
	0x00,
}
