// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sportsbook/api/resulted/sportsbook.proto

/*
Package resulted is a generated protocol buffer package.

It is generated from these files:
	sportsbook/api/resulted/sportsbook.proto

It has these top-level messages:
	EventMetadata
	SoccerMetadata
	SoccerMetadataV2
	TennisMetadata
	BasketballMetadata
	IceHockeyMetadata
	HandballMetadata
	TableTennisMetadata
	BaseballMetadata
	AmericanFootballMetadata
	SnookerMetadata
	DartsMetadata
	FutsalMetadata
	BowlsMetadata
	CricketMetadata
*/
package resulted

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventMetadata struct {
	EventStatus  string                          `protobuf:"bytes,1,opt,name=event_status,json=eventStatus" json:"event_status,omitempty"`
	Score        []int32                         `protobuf:"varint,2,rep,packed,name=score" json:"score,omitempty"`
	SetScores    []*EventMetadata_Set            `protobuf:"bytes,3,rep,name=set_scores,json=setScores" json:"set_scores,omitempty"`
	ClearedScore []int32                         `protobuf:"varint,4,rep,packed,name=cleared_score,json=clearedScore" json:"cleared_score,omitempty"`
	ScoreList    []*EventMetadata_SummaryListing `protobuf:"bytes,7,rep,name=score_list,json=scoreList" json:"score_list,omitempty"`
	CardList     []*EventMetadata_SummaryListing `protobuf:"bytes,8,rep,name=card_list,json=cardList" json:"card_list,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//	*EventMetadata_Soccer
	//	*EventMetadata_SoccerV2
	//	*EventMetadata_Tennis
	//	*EventMetadata_Basketball
	//	*EventMetadata_IceHockey
	//	*EventMetadata_Handball
	//	*EventMetadata_TableTennis
	//	*EventMetadata_Baseball
	//	*EventMetadata_AmericanFootball
	//	*EventMetadata_Snooker
	//	*EventMetadata_Darts
	//	*EventMetadata_Futsal
	//	*EventMetadata_Bowls
	//	*EventMetadata_Cricket
	Metadata isEventMetadata_Metadata `protobuf_oneof:"metadata"`
}

func (m *EventMetadata) Reset()                    { *m = EventMetadata{} }
func (m *EventMetadata) String() string            { return proto.CompactTextString(m) }
func (*EventMetadata) ProtoMessage()               {}
func (*EventMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isEventMetadata_Metadata interface{ isEventMetadata_Metadata() }

type EventMetadata_Soccer struct {
	Soccer *SoccerMetadata `protobuf:"bytes,9,opt,name=soccer,oneof"`
}
type EventMetadata_SoccerV2 struct {
	SoccerV2 *SoccerMetadataV2 `protobuf:"bytes,23,opt,name=soccer_v2,json=soccerV2,oneof"`
}
type EventMetadata_Tennis struct {
	Tennis *TennisMetadata `protobuf:"bytes,10,opt,name=tennis,oneof"`
}
type EventMetadata_Basketball struct {
	Basketball *BasketballMetadata `protobuf:"bytes,11,opt,name=basketball,oneof"`
}
type EventMetadata_IceHockey struct {
	IceHockey *IceHockeyMetadata `protobuf:"bytes,12,opt,name=ice_hockey,json=iceHockey,oneof"`
}
type EventMetadata_Handball struct {
	Handball *HandballMetadata `protobuf:"bytes,13,opt,name=handball,oneof"`
}
type EventMetadata_TableTennis struct {
	TableTennis *TableTennisMetadata `protobuf:"bytes,14,opt,name=table_tennis,json=tableTennis,oneof"`
}
type EventMetadata_Baseball struct {
	Baseball *BaseballMetadata `protobuf:"bytes,15,opt,name=baseball,oneof"`
}
type EventMetadata_AmericanFootball struct {
	AmericanFootball *AmericanFootballMetadata `protobuf:"bytes,16,opt,name=american_football,json=americanFootball,oneof"`
}
type EventMetadata_Snooker struct {
	Snooker *SnookerMetadata `protobuf:"bytes,17,opt,name=snooker,oneof"`
}
type EventMetadata_Darts struct {
	Darts *DartsMetadata `protobuf:"bytes,18,opt,name=darts,oneof"`
}
type EventMetadata_Futsal struct {
	Futsal *FutsalMetadata `protobuf:"bytes,19,opt,name=futsal,oneof"`
}
type EventMetadata_Bowls struct {
	Bowls *BowlsMetadata `protobuf:"bytes,20,opt,name=bowls,oneof"`
}
type EventMetadata_Cricket struct {
	Cricket *CricketMetadata `protobuf:"bytes,21,opt,name=cricket,oneof"`
}

func (*EventMetadata_Soccer) isEventMetadata_Metadata()           {}
func (*EventMetadata_SoccerV2) isEventMetadata_Metadata()         {}
func (*EventMetadata_Tennis) isEventMetadata_Metadata()           {}
func (*EventMetadata_Basketball) isEventMetadata_Metadata()       {}
func (*EventMetadata_IceHockey) isEventMetadata_Metadata()        {}
func (*EventMetadata_Handball) isEventMetadata_Metadata()         {}
func (*EventMetadata_TableTennis) isEventMetadata_Metadata()      {}
func (*EventMetadata_Baseball) isEventMetadata_Metadata()         {}
func (*EventMetadata_AmericanFootball) isEventMetadata_Metadata() {}
func (*EventMetadata_Snooker) isEventMetadata_Metadata()          {}
func (*EventMetadata_Darts) isEventMetadata_Metadata()            {}
func (*EventMetadata_Futsal) isEventMetadata_Metadata()           {}
func (*EventMetadata_Bowls) isEventMetadata_Metadata()            {}
func (*EventMetadata_Cricket) isEventMetadata_Metadata()          {}

func (m *EventMetadata) GetMetadata() isEventMetadata_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EventMetadata) GetEventStatus() string {
	if m != nil {
		return m.EventStatus
	}
	return ""
}

func (m *EventMetadata) GetScore() []int32 {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *EventMetadata) GetSetScores() []*EventMetadata_Set {
	if m != nil {
		return m.SetScores
	}
	return nil
}

func (m *EventMetadata) GetClearedScore() []int32 {
	if m != nil {
		return m.ClearedScore
	}
	return nil
}

func (m *EventMetadata) GetScoreList() []*EventMetadata_SummaryListing {
	if m != nil {
		return m.ScoreList
	}
	return nil
}

func (m *EventMetadata) GetCardList() []*EventMetadata_SummaryListing {
	if m != nil {
		return m.CardList
	}
	return nil
}

func (m *EventMetadata) GetSoccer() *SoccerMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Soccer); ok {
		return x.Soccer
	}
	return nil
}

func (m *EventMetadata) GetSoccerV2() *SoccerMetadataV2 {
	if x, ok := m.GetMetadata().(*EventMetadata_SoccerV2); ok {
		return x.SoccerV2
	}
	return nil
}

func (m *EventMetadata) GetTennis() *TennisMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Tennis); ok {
		return x.Tennis
	}
	return nil
}

func (m *EventMetadata) GetBasketball() *BasketballMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Basketball); ok {
		return x.Basketball
	}
	return nil
}

func (m *EventMetadata) GetIceHockey() *IceHockeyMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_IceHockey); ok {
		return x.IceHockey
	}
	return nil
}

func (m *EventMetadata) GetHandball() *HandballMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Handball); ok {
		return x.Handball
	}
	return nil
}

func (m *EventMetadata) GetTableTennis() *TableTennisMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_TableTennis); ok {
		return x.TableTennis
	}
	return nil
}

func (m *EventMetadata) GetBaseball() *BaseballMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Baseball); ok {
		return x.Baseball
	}
	return nil
}

func (m *EventMetadata) GetAmericanFootball() *AmericanFootballMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_AmericanFootball); ok {
		return x.AmericanFootball
	}
	return nil
}

func (m *EventMetadata) GetSnooker() *SnookerMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Snooker); ok {
		return x.Snooker
	}
	return nil
}

func (m *EventMetadata) GetDarts() *DartsMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Darts); ok {
		return x.Darts
	}
	return nil
}

func (m *EventMetadata) GetFutsal() *FutsalMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Futsal); ok {
		return x.Futsal
	}
	return nil
}

func (m *EventMetadata) GetBowls() *BowlsMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Bowls); ok {
		return x.Bowls
	}
	return nil
}

func (m *EventMetadata) GetCricket() *CricketMetadata {
	if x, ok := m.GetMetadata().(*EventMetadata_Cricket); ok {
		return x.Cricket
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EventMetadata) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EventMetadata_OneofMarshaler, _EventMetadata_OneofUnmarshaler, _EventMetadata_OneofSizer, []interface{}{
		(*EventMetadata_Soccer)(nil),
		(*EventMetadata_SoccerV2)(nil),
		(*EventMetadata_Tennis)(nil),
		(*EventMetadata_Basketball)(nil),
		(*EventMetadata_IceHockey)(nil),
		(*EventMetadata_Handball)(nil),
		(*EventMetadata_TableTennis)(nil),
		(*EventMetadata_Baseball)(nil),
		(*EventMetadata_AmericanFootball)(nil),
		(*EventMetadata_Snooker)(nil),
		(*EventMetadata_Darts)(nil),
		(*EventMetadata_Futsal)(nil),
		(*EventMetadata_Bowls)(nil),
		(*EventMetadata_Cricket)(nil),
	}
}

func _EventMetadata_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EventMetadata)
	// metadata
	switch x := m.Metadata.(type) {
	case *EventMetadata_Soccer:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Soccer); err != nil {
			return err
		}
	case *EventMetadata_SoccerV2:
		b.EncodeVarint(23<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SoccerV2); err != nil {
			return err
		}
	case *EventMetadata_Tennis:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tennis); err != nil {
			return err
		}
	case *EventMetadata_Basketball:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Basketball); err != nil {
			return err
		}
	case *EventMetadata_IceHockey:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IceHockey); err != nil {
			return err
		}
	case *EventMetadata_Handball:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Handball); err != nil {
			return err
		}
	case *EventMetadata_TableTennis:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TableTennis); err != nil {
			return err
		}
	case *EventMetadata_Baseball:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Baseball); err != nil {
			return err
		}
	case *EventMetadata_AmericanFootball:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AmericanFootball); err != nil {
			return err
		}
	case *EventMetadata_Snooker:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Snooker); err != nil {
			return err
		}
	case *EventMetadata_Darts:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Darts); err != nil {
			return err
		}
	case *EventMetadata_Futsal:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Futsal); err != nil {
			return err
		}
	case *EventMetadata_Bowls:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Bowls); err != nil {
			return err
		}
	case *EventMetadata_Cricket:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cricket); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EventMetadata.Metadata has unexpected type %T", x)
	}
	return nil
}

func _EventMetadata_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EventMetadata)
	switch tag {
	case 9: // metadata.soccer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SoccerMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Soccer{msg}
		return true, err
	case 23: // metadata.soccer_v2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SoccerMetadataV2)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_SoccerV2{msg}
		return true, err
	case 10: // metadata.tennis
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TennisMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Tennis{msg}
		return true, err
	case 11: // metadata.basketball
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BasketballMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Basketball{msg}
		return true, err
	case 12: // metadata.ice_hockey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IceHockeyMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_IceHockey{msg}
		return true, err
	case 13: // metadata.handball
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HandballMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Handball{msg}
		return true, err
	case 14: // metadata.table_tennis
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TableTennisMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_TableTennis{msg}
		return true, err
	case 15: // metadata.baseball
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseballMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Baseball{msg}
		return true, err
	case 16: // metadata.american_football
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AmericanFootballMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_AmericanFootball{msg}
		return true, err
	case 17: // metadata.snooker
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SnookerMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Snooker{msg}
		return true, err
	case 18: // metadata.darts
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DartsMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Darts{msg}
		return true, err
	case 19: // metadata.futsal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FutsalMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Futsal{msg}
		return true, err
	case 20: // metadata.bowls
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BowlsMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Bowls{msg}
		return true, err
	case 21: // metadata.cricket
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CricketMetadata)
		err := b.DecodeMessage(msg)
		m.Metadata = &EventMetadata_Cricket{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EventMetadata_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EventMetadata)
	// metadata
	switch x := m.Metadata.(type) {
	case *EventMetadata_Soccer:
		s := proto.Size(x.Soccer)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_SoccerV2:
		s := proto.Size(x.SoccerV2)
		n += proto.SizeVarint(23<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Tennis:
		s := proto.Size(x.Tennis)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Basketball:
		s := proto.Size(x.Basketball)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_IceHockey:
		s := proto.Size(x.IceHockey)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Handball:
		s := proto.Size(x.Handball)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_TableTennis:
		s := proto.Size(x.TableTennis)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Baseball:
		s := proto.Size(x.Baseball)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_AmericanFootball:
		s := proto.Size(x.AmericanFootball)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Snooker:
		s := proto.Size(x.Snooker)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Darts:
		s := proto.Size(x.Darts)
		n += proto.SizeVarint(18<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Futsal:
		s := proto.Size(x.Futsal)
		n += proto.SizeVarint(19<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Bowls:
		s := proto.Size(x.Bowls)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventMetadata_Cricket:
		s := proto.Size(x.Cricket)
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EventMetadata_Set struct {
	Score []int32 `protobuf:"varint,1,rep,packed,name=score" json:"score,omitempty"`
}

func (m *EventMetadata_Set) Reset()                    { *m = EventMetadata_Set{} }
func (m *EventMetadata_Set) String() string            { return proto.CompactTextString(m) }
func (*EventMetadata_Set) ProtoMessage()               {}
func (*EventMetadata_Set) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *EventMetadata_Set) GetScore() []int32 {
	if m != nil {
		return m.Score
	}
	return nil
}

type EventMetadata_SummaryListing struct {
	Cancelled  string `protobuf:"bytes,1,opt,name=cancelled" json:"cancelled,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	PlayerId   uint32 `protobuf:"varint,3,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	TeamName   string `protobuf:"bytes,4,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	TeamId     uint32 `protobuf:"varint,5,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	Time       string `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	HomeScore  int32  `protobuf:"varint,7,opt,name=home_score,json=homeScore" json:"home_score,omitempty"`
	AwayScore  int32  `protobuf:"varint,8,opt,name=away_score,json=awayScore" json:"away_score,omitempty"`
	Type       string `protobuf:"bytes,9,opt,name=type" json:"type,omitempty"`
}

func (m *EventMetadata_SummaryListing) Reset()                    { *m = EventMetadata_SummaryListing{} }
func (m *EventMetadata_SummaryListing) String() string            { return proto.CompactTextString(m) }
func (*EventMetadata_SummaryListing) ProtoMessage()               {}
func (*EventMetadata_SummaryListing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *EventMetadata_SummaryListing) GetCancelled() string {
	if m != nil {
		return m.Cancelled
	}
	return ""
}

func (m *EventMetadata_SummaryListing) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *EventMetadata_SummaryListing) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *EventMetadata_SummaryListing) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *EventMetadata_SummaryListing) GetTeamId() uint32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *EventMetadata_SummaryListing) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *EventMetadata_SummaryListing) GetHomeScore() int32 {
	if m != nil {
		return m.HomeScore
	}
	return 0
}

func (m *EventMetadata_SummaryListing) GetAwayScore() int32 {
	if m != nil {
		return m.AwayScore
	}
	return 0
}

func (m *EventMetadata_SummaryListing) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SoccerMetadata struct {
	CornersAway        int32 `protobuf:"varint,1,opt,name=corners_away,json=cornersAway" json:"corners_away,omitempty"`
	CornersHome        int32 `protobuf:"varint,2,opt,name=corners_home,json=cornersHome" json:"corners_home,omitempty"`
	RedCardsAway       int32 `protobuf:"varint,3,opt,name=red_cards_away,json=redCardsAway" json:"red_cards_away,omitempty"`
	RedCardsHome       int32 `protobuf:"varint,4,opt,name=red_cards_home,json=redCardsHome" json:"red_cards_home,omitempty"`
	YellowCardsAway    int32 `protobuf:"varint,5,opt,name=yellow_cards_away,json=yellowCardsAway" json:"yellow_cards_away,omitempty"`
	YellowCardsHome    int32 `protobuf:"varint,6,opt,name=yellow_cards_home,json=yellowCardsHome" json:"yellow_cards_home,omitempty"`
	YellowRedCardsAway int32 `protobuf:"varint,7,opt,name=yellow_red_cards_away,json=yellowRedCardsAway" json:"yellow_red_cards_away,omitempty"`
	YellowRedCardsHome int32 `protobuf:"varint,8,opt,name=yellow_red_cards_home,json=yellowRedCardsHome" json:"yellow_red_cards_home,omitempty"`
}

func (m *SoccerMetadata) Reset()                    { *m = SoccerMetadata{} }
func (m *SoccerMetadata) String() string            { return proto.CompactTextString(m) }
func (*SoccerMetadata) ProtoMessage()               {}
func (*SoccerMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SoccerMetadata) GetCornersAway() int32 {
	if m != nil {
		return m.CornersAway
	}
	return 0
}

func (m *SoccerMetadata) GetCornersHome() int32 {
	if m != nil {
		return m.CornersHome
	}
	return 0
}

func (m *SoccerMetadata) GetRedCardsAway() int32 {
	if m != nil {
		return m.RedCardsAway
	}
	return 0
}

func (m *SoccerMetadata) GetRedCardsHome() int32 {
	if m != nil {
		return m.RedCardsHome
	}
	return 0
}

func (m *SoccerMetadata) GetYellowCardsAway() int32 {
	if m != nil {
		return m.YellowCardsAway
	}
	return 0
}

func (m *SoccerMetadata) GetYellowCardsHome() int32 {
	if m != nil {
		return m.YellowCardsHome
	}
	return 0
}

func (m *SoccerMetadata) GetYellowRedCardsAway() int32 {
	if m != nil {
		return m.YellowRedCardsAway
	}
	return 0
}

func (m *SoccerMetadata) GetYellowRedCardsHome() int32 {
	if m != nil {
		return m.YellowRedCardsHome
	}
	return 0
}

type SoccerMetadataV2 struct {
	CornersAway        string `protobuf:"bytes,1,opt,name=corners_away,json=cornersAway" json:"corners_away,omitempty"`
	CornersHome        string `protobuf:"bytes,2,opt,name=corners_home,json=cornersHome" json:"corners_home,omitempty"`
	RedCardsAway       string `protobuf:"bytes,3,opt,name=red_cards_away,json=redCardsAway" json:"red_cards_away,omitempty"`
	RedCardsHome       string `protobuf:"bytes,4,opt,name=red_cards_home,json=redCardsHome" json:"red_cards_home,omitempty"`
	YellowCardsAway    string `protobuf:"bytes,5,opt,name=yellow_cards_away,json=yellowCardsAway" json:"yellow_cards_away,omitempty"`
	YellowCardsHome    string `protobuf:"bytes,6,opt,name=yellow_cards_home,json=yellowCardsHome" json:"yellow_cards_home,omitempty"`
	YellowRedCardsAway string `protobuf:"bytes,7,opt,name=yellow_red_cards_away,json=yellowRedCardsAway" json:"yellow_red_cards_away,omitempty"`
	YellowRedCardsHome string `protobuf:"bytes,8,opt,name=yellow_red_cards_home,json=yellowRedCardsHome" json:"yellow_red_cards_home,omitempty"`
	HomeScore          string `protobuf:"bytes,9,opt,name=home_score,json=homeScore" json:"home_score,omitempty"`
	AwayScore          string `protobuf:"bytes,10,opt,name=away_score,json=awayScore" json:"away_score,omitempty"`
	EventStatus        string `protobuf:"bytes,11,opt,name=event_status,json=eventStatus" json:"event_status,omitempty"`
}

func (m *SoccerMetadataV2) Reset()                    { *m = SoccerMetadataV2{} }
func (m *SoccerMetadataV2) String() string            { return proto.CompactTextString(m) }
func (*SoccerMetadataV2) ProtoMessage()               {}
func (*SoccerMetadataV2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SoccerMetadataV2) GetCornersAway() string {
	if m != nil {
		return m.CornersAway
	}
	return ""
}

func (m *SoccerMetadataV2) GetCornersHome() string {
	if m != nil {
		return m.CornersHome
	}
	return ""
}

func (m *SoccerMetadataV2) GetRedCardsAway() string {
	if m != nil {
		return m.RedCardsAway
	}
	return ""
}

func (m *SoccerMetadataV2) GetRedCardsHome() string {
	if m != nil {
		return m.RedCardsHome
	}
	return ""
}

func (m *SoccerMetadataV2) GetYellowCardsAway() string {
	if m != nil {
		return m.YellowCardsAway
	}
	return ""
}

func (m *SoccerMetadataV2) GetYellowCardsHome() string {
	if m != nil {
		return m.YellowCardsHome
	}
	return ""
}

func (m *SoccerMetadataV2) GetYellowRedCardsAway() string {
	if m != nil {
		return m.YellowRedCardsAway
	}
	return ""
}

func (m *SoccerMetadataV2) GetYellowRedCardsHome() string {
	if m != nil {
		return m.YellowRedCardsHome
	}
	return ""
}

func (m *SoccerMetadataV2) GetHomeScore() string {
	if m != nil {
		return m.HomeScore
	}
	return ""
}

func (m *SoccerMetadataV2) GetAwayScore() string {
	if m != nil {
		return m.AwayScore
	}
	return ""
}

func (m *SoccerMetadataV2) GetEventStatus() string {
	if m != nil {
		return m.EventStatus
	}
	return ""
}

type TennisMetadata struct {
	GameScore []int32 `protobuf:"varint,5,rep,packed,name=game_score,json=gameScore" json:"game_score,omitempty"`
}

func (m *TennisMetadata) Reset()                    { *m = TennisMetadata{} }
func (m *TennisMetadata) String() string            { return proto.CompactTextString(m) }
func (*TennisMetadata) ProtoMessage()               {}
func (*TennisMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TennisMetadata) GetGameScore() []int32 {
	if m != nil {
		return m.GameScore
	}
	return nil
}

type BasketballMetadata struct {
}

func (m *BasketballMetadata) Reset()                    { *m = BasketballMetadata{} }
func (m *BasketballMetadata) String() string            { return proto.CompactTextString(m) }
func (*BasketballMetadata) ProtoMessage()               {}
func (*BasketballMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type IceHockeyMetadata struct {
}

func (m *IceHockeyMetadata) Reset()                    { *m = IceHockeyMetadata{} }
func (m *IceHockeyMetadata) String() string            { return proto.CompactTextString(m) }
func (*IceHockeyMetadata) ProtoMessage()               {}
func (*IceHockeyMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type HandballMetadata struct {
}

func (m *HandballMetadata) Reset()                    { *m = HandballMetadata{} }
func (m *HandballMetadata) String() string            { return proto.CompactTextString(m) }
func (*HandballMetadata) ProtoMessage()               {}
func (*HandballMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type TableTennisMetadata struct {
}

func (m *TableTennisMetadata) Reset()                    { *m = TableTennisMetadata{} }
func (m *TableTennisMetadata) String() string            { return proto.CompactTextString(m) }
func (*TableTennisMetadata) ProtoMessage()               {}
func (*TableTennisMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BaseballMetadata struct {
	AwayPitcher string `protobuf:"bytes,7,opt,name=away_pitcher,json=awayPitcher" json:"away_pitcher,omitempty"`
	HomePitcher string `protobuf:"bytes,8,opt,name=home_pitcher,json=homePitcher" json:"home_pitcher,omitempty"`
}

func (m *BaseballMetadata) Reset()                    { *m = BaseballMetadata{} }
func (m *BaseballMetadata) String() string            { return proto.CompactTextString(m) }
func (*BaseballMetadata) ProtoMessage()               {}
func (*BaseballMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BaseballMetadata) GetAwayPitcher() string {
	if m != nil {
		return m.AwayPitcher
	}
	return ""
}

func (m *BaseballMetadata) GetHomePitcher() string {
	if m != nil {
		return m.HomePitcher
	}
	return ""
}

type AmericanFootballMetadata struct {
	Possession int32 `protobuf:"varint,1,opt,name=possession" json:"possession,omitempty"`
}

func (m *AmericanFootballMetadata) Reset()                    { *m = AmericanFootballMetadata{} }
func (m *AmericanFootballMetadata) String() string            { return proto.CompactTextString(m) }
func (*AmericanFootballMetadata) ProtoMessage()               {}
func (*AmericanFootballMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AmericanFootballMetadata) GetPossession() int32 {
	if m != nil {
		return m.Possession
	}
	return 0
}

type SnookerMetadata struct {
}

func (m *SnookerMetadata) Reset()                    { *m = SnookerMetadata{} }
func (m *SnookerMetadata) String() string            { return proto.CompactTextString(m) }
func (*SnookerMetadata) ProtoMessage()               {}
func (*SnookerMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type DartsMetadata struct {
	LegScore int32 `protobuf:"varint,1,opt,name=leg_score,json=legScore" json:"leg_score,omitempty"`
}

func (m *DartsMetadata) Reset()                    { *m = DartsMetadata{} }
func (m *DartsMetadata) String() string            { return proto.CompactTextString(m) }
func (*DartsMetadata) ProtoMessage()               {}
func (*DartsMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DartsMetadata) GetLegScore() int32 {
	if m != nil {
		return m.LegScore
	}
	return 0
}

type FutsalMetadata struct {
}

func (m *FutsalMetadata) Reset()                    { *m = FutsalMetadata{} }
func (m *FutsalMetadata) String() string            { return proto.CompactTextString(m) }
func (*FutsalMetadata) ProtoMessage()               {}
func (*FutsalMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type BowlsMetadata struct {
}

func (m *BowlsMetadata) Reset()                    { *m = BowlsMetadata{} }
func (m *BowlsMetadata) String() string            { return proto.CompactTextString(m) }
func (*BowlsMetadata) ProtoMessage()               {}
func (*BowlsMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type CricketMetadata struct {
	DismissalsAway     int32  `protobuf:"varint,1,opt,name=dismissals_away,json=dismissalsAway" json:"dismissals_away,omitempty"`
	DismissalsHome     int32  `protobuf:"varint,2,opt,name=dismissals_home,json=dismissalsHome" json:"dismissals_home,omitempty"`
	Over               int32  `protobuf:"varint,3,opt,name=over" json:"over,omitempty"`
	Innings            int32  `protobuf:"varint,4,opt,name=innings" json:"innings,omitempty"`
	PenaltyRunsHome    int32  `protobuf:"varint,5,opt,name=penalty_runs_home,json=penaltyRunsHome" json:"penalty_runs_home,omitempty"`
	PenaltyRunsAway    int32  `protobuf:"varint,6,opt,name=penalty_runs_away,json=penaltyRunsAway" json:"penalty_runs_away,omitempty"`
	HomeRuns           int32  `protobuf:"varint,9,opt,name=home_runs,json=homeRuns" json:"home_runs,omitempty"`
	AwayRuns           int32  `protobuf:"varint,10,opt,name=away_runs,json=awayRuns" json:"away_runs,omitempty"`
	HomeWickets        int32  `protobuf:"varint,11,opt,name=home_wickets,json=homeWickets" json:"home_wickets,omitempty"`
	AwayWickets        int32  `protobuf:"varint,12,opt,name=away_wickets,json=awayWickets" json:"away_wickets,omitempty"`
	TossTime           int64  `protobuf:"varint,13,opt,name=toss_time,json=tossTime" json:"toss_time,omitempty"`
	StartBattingTeam   uint32 `protobuf:"varint,14,opt,name=start_batting_team,json=startBattingTeam" json:"start_batting_team,omitempty"`
	CurrentBattingTeam uint32 `protobuf:"varint,15,opt,name=current_batting_team,json=currentBattingTeam" json:"current_batting_team,omitempty"`
	TossWinner         uint32 `protobuf:"varint,16,opt,name=toss_winner,json=tossWinner" json:"toss_winner,omitempty"`
	HomeTotalOvers     uint32 `protobuf:"varint,17,opt,name=home_total_overs,json=homeTotalOvers" json:"home_total_overs,omitempty"`
	AwayTotalOvers     uint32 `protobuf:"varint,18,opt,name=away_total_overs,json=awayTotalOvers" json:"away_total_overs,omitempty"`
	HomeOver           uint32 `protobuf:"varint,19,opt,name=home_over,json=homeOver" json:"home_over,omitempty"`
	AwayOver           uint32 `protobuf:"varint,20,opt,name=away_over,json=awayOver" json:"away_over,omitempty"`
	HomeBalls          string `protobuf:"bytes,21,opt,name=home_balls,json=homeBalls" json:"home_balls,omitempty"`
	AwayBalls          string `protobuf:"bytes,22,opt,name=away_balls,json=awayBalls" json:"away_balls,omitempty"`
}

func (m *CricketMetadata) Reset()                    { *m = CricketMetadata{} }
func (m *CricketMetadata) String() string            { return proto.CompactTextString(m) }
func (*CricketMetadata) ProtoMessage()               {}
func (*CricketMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CricketMetadata) GetDismissalsAway() int32 {
	if m != nil {
		return m.DismissalsAway
	}
	return 0
}

func (m *CricketMetadata) GetDismissalsHome() int32 {
	if m != nil {
		return m.DismissalsHome
	}
	return 0
}

func (m *CricketMetadata) GetOver() int32 {
	if m != nil {
		return m.Over
	}
	return 0
}

func (m *CricketMetadata) GetInnings() int32 {
	if m != nil {
		return m.Innings
	}
	return 0
}

func (m *CricketMetadata) GetPenaltyRunsHome() int32 {
	if m != nil {
		return m.PenaltyRunsHome
	}
	return 0
}

func (m *CricketMetadata) GetPenaltyRunsAway() int32 {
	if m != nil {
		return m.PenaltyRunsAway
	}
	return 0
}

func (m *CricketMetadata) GetHomeRuns() int32 {
	if m != nil {
		return m.HomeRuns
	}
	return 0
}

func (m *CricketMetadata) GetAwayRuns() int32 {
	if m != nil {
		return m.AwayRuns
	}
	return 0
}

func (m *CricketMetadata) GetHomeWickets() int32 {
	if m != nil {
		return m.HomeWickets
	}
	return 0
}

func (m *CricketMetadata) GetAwayWickets() int32 {
	if m != nil {
		return m.AwayWickets
	}
	return 0
}

func (m *CricketMetadata) GetTossTime() int64 {
	if m != nil {
		return m.TossTime
	}
	return 0
}

func (m *CricketMetadata) GetStartBattingTeam() uint32 {
	if m != nil {
		return m.StartBattingTeam
	}
	return 0
}

func (m *CricketMetadata) GetCurrentBattingTeam() uint32 {
	if m != nil {
		return m.CurrentBattingTeam
	}
	return 0
}

func (m *CricketMetadata) GetTossWinner() uint32 {
	if m != nil {
		return m.TossWinner
	}
	return 0
}

func (m *CricketMetadata) GetHomeTotalOvers() uint32 {
	if m != nil {
		return m.HomeTotalOvers
	}
	return 0
}

func (m *CricketMetadata) GetAwayTotalOvers() uint32 {
	if m != nil {
		return m.AwayTotalOvers
	}
	return 0
}

func (m *CricketMetadata) GetHomeOver() uint32 {
	if m != nil {
		return m.HomeOver
	}
	return 0
}

func (m *CricketMetadata) GetAwayOver() uint32 {
	if m != nil {
		return m.AwayOver
	}
	return 0
}

func (m *CricketMetadata) GetHomeBalls() string {
	if m != nil {
		return m.HomeBalls
	}
	return ""
}

func (m *CricketMetadata) GetAwayBalls() string {
	if m != nil {
		return m.AwayBalls
	}
	return ""
}

func init() {
	proto.RegisterType((*EventMetadata)(nil), "resulted.EventMetadata")
	proto.RegisterType((*EventMetadata_Set)(nil), "resulted.EventMetadata.Set")
	proto.RegisterType((*EventMetadata_SummaryListing)(nil), "resulted.EventMetadata.SummaryListing")
	proto.RegisterType((*SoccerMetadata)(nil), "resulted.SoccerMetadata")
	proto.RegisterType((*SoccerMetadataV2)(nil), "resulted.SoccerMetadataV2")
	proto.RegisterType((*TennisMetadata)(nil), "resulted.TennisMetadata")
	proto.RegisterType((*BasketballMetadata)(nil), "resulted.BasketballMetadata")
	proto.RegisterType((*IceHockeyMetadata)(nil), "resulted.IceHockeyMetadata")
	proto.RegisterType((*HandballMetadata)(nil), "resulted.HandballMetadata")
	proto.RegisterType((*TableTennisMetadata)(nil), "resulted.TableTennisMetadata")
	proto.RegisterType((*BaseballMetadata)(nil), "resulted.BaseballMetadata")
	proto.RegisterType((*AmericanFootballMetadata)(nil), "resulted.AmericanFootballMetadata")
	proto.RegisterType((*SnookerMetadata)(nil), "resulted.SnookerMetadata")
	proto.RegisterType((*DartsMetadata)(nil), "resulted.DartsMetadata")
	proto.RegisterType((*FutsalMetadata)(nil), "resulted.FutsalMetadata")
	proto.RegisterType((*BowlsMetadata)(nil), "resulted.BowlsMetadata")
	proto.RegisterType((*CricketMetadata)(nil), "resulted.CricketMetadata")
}

func init() { proto.RegisterFile("sportsbook/api/resulted/sportsbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x6d, 0x6e, 0xdb, 0x46,
	0x10, 0x8d, 0x23, 0xcb, 0x26, 0x47, 0xd6, 0x87, 0xd7, 0x4e, 0xc3, 0xc6, 0x49, 0xe3, 0xb2, 0x45,
	0xa3, 0x16, 0x81, 0xdd, 0xba, 0x28, 0xd0, 0x06, 0x45, 0x81, 0x28, 0x4d, 0xe0, 0x00, 0xfd, 0xa4,
	0x8d, 0xa4, 0xff, 0x88, 0x15, 0xb9, 0xb1, 0x09, 0xf3, 0x43, 0xe0, 0xae, 0x62, 0xe8, 0x06, 0xbd,
	0x42, 0xcf, 0xd3, 0x23, 0xf4, 0x02, 0x3d, 0x4a, 0x31, 0xb3, 0x4b, 0x71, 0x49, 0xd9, 0xa8, 0xfd,
	0x4f, 0x7c, 0xef, 0xcd, 0x0c, 0x77, 0xb8, 0xfb, 0x66, 0x05, 0x63, 0x39, 0x2b, 0x4a, 0x25, 0xa7,
	0x45, 0x71, 0x71, 0xc8, 0x67, 0xc9, 0x61, 0x29, 0xe4, 0x3c, 0x55, 0x22, 0x3e, 0xac, 0xf1, 0x83,
	0x59, 0x59, 0xa8, 0x82, 0x39, 0x15, 0xe5, 0xff, 0xd5, 0x83, 0xfe, 0xcb, 0xf7, 0x22, 0x57, 0x3f,
	0x0b, 0xc5, 0x63, 0xae, 0x38, 0xfb, 0x18, 0xb6, 0x04, 0x02, 0xa1, 0x54, 0x5c, 0xcd, 0xa5, 0xb7,
	0xb6, 0xbf, 0x36, 0x76, 0x83, 0x1e, 0x61, 0x27, 0x04, 0xb1, 0x5d, 0xe8, 0xca, 0xa8, 0x28, 0x85,
	0x77, 0x77, 0xbf, 0x33, 0xee, 0x06, 0xfa, 0x81, 0x3d, 0x03, 0x90, 0x42, 0x85, 0xf4, 0x20, 0xbd,
	0xce, 0x7e, 0x67, 0xdc, 0x3b, 0xda, 0x3b, 0xa8, 0x2a, 0x1d, 0x34, 0xaa, 0x1c, 0x9c, 0x08, 0x15,
	0xb8, 0x52, 0xa8, 0x13, 0x52, 0xb3, 0x4f, 0xa0, 0x1f, 0xa5, 0x82, 0x97, 0x22, 0xd6, 0xf1, 0xde,
	0x3a, 0x65, 0xde, 0x32, 0x20, 0xa9, 0xd8, 0x4b, 0x00, 0x22, 0xc3, 0x34, 0x91, 0xca, 0xdb, 0xa4,
	0x02, 0x9f, 0x5d, 0x5b, 0x60, 0x9e, 0x65, 0xbc, 0x5c, 0xfc, 0x94, 0x48, 0x95, 0xe4, 0x67, 0x81,
	0x4b, 0x91, 0xf8, 0xc4, 0x5e, 0x80, 0x1b, 0xf1, 0x32, 0xd6, 0x59, 0x9c, 0x5b, 0x65, 0x71, 0x30,
	0x90, 0x92, 0x1c, 0xc1, 0x86, 0x2c, 0xa2, 0x48, 0x94, 0x9e, 0xbb, 0xbf, 0x36, 0xee, 0x1d, 0x79,
	0x75, 0x86, 0x13, 0xc2, 0xab, 0x14, 0xc7, 0x77, 0x02, 0xa3, 0x64, 0xdf, 0x81, 0xab, 0x7f, 0x85,
	0xef, 0x8f, 0xbc, 0xfb, 0x14, 0xf6, 0xe0, 0xba, 0xb0, 0x37, 0x47, 0xc7, 0x77, 0x02, 0x47, 0xcb,
	0xdf, 0x1c, 0x61, 0x39, 0x25, 0xf2, 0x3c, 0x91, 0x1e, 0xb4, 0xcb, 0x9d, 0x12, 0x6e, 0x97, 0xd3,
	0x4a, 0xf6, 0x03, 0xc0, 0x94, 0xcb, 0x0b, 0xa1, 0xa6, 0x3c, 0x4d, 0xbd, 0x1e, 0xc5, 0x3d, 0xac,
	0xe3, 0x26, 0x4b, 0xce, 0x8a, 0xb5, 0x22, 0xd8, 0xf7, 0x00, 0x49, 0x24, 0xc2, 0xf3, 0x22, 0xba,
	0x10, 0x0b, 0x6f, 0x8b, 0xe2, 0xad, 0xef, 0xf9, 0x3a, 0x12, 0xc7, 0x44, 0x59, 0xe1, 0x6e, 0x52,
	0x81, 0xec, 0x5b, 0x70, 0xce, 0x79, 0x1e, 0x53, 0xed, 0x7e, 0x7b, 0xad, 0xc7, 0x86, 0xb1, 0x42,
	0x97, 0x6a, 0x36, 0x81, 0x2d, 0xc5, 0xa7, 0xa9, 0x08, 0xcd, 0x8a, 0x07, 0x14, 0xfd, 0xc8, 0x5a,
	0x31, 0xb2, 0x2b, 0xcb, 0xee, 0xa9, 0x1a, 0xc6, 0xea, 0x53, 0x2e, 0x05, 0x55, 0x1f, 0xb6, 0xab,
	0x4f, 0x0c, 0x63, 0x57, 0xaf, 0xd4, 0xec, 0x77, 0xd8, 0xe6, 0x99, 0x28, 0x93, 0x88, 0xe7, 0xe1,
	0xbb, 0xa2, 0xd0, 0xcd, 0x1b, 0x51, 0x0a, 0xbf, 0x4e, 0xf1, 0xdc, 0x48, 0x5e, 0x19, 0x85, 0x95,
	0x6a, 0xc4, 0x5b, 0x1c, 0xfb, 0x06, 0x36, 0x65, 0x5e, 0x14, 0x17, 0xa2, 0xf4, 0xb6, 0x29, 0xd1,
	0x87, 0xd6, 0x57, 0xd7, 0x84, 0x15, 0x5f, 0x69, 0xd9, 0x21, 0x74, 0x63, 0x5e, 0x2a, 0xe9, 0x31,
	0x0a, 0xba, 0x5f, 0x07, 0xfd, 0x88, 0xb0, 0x15, 0xa2, 0x75, 0xb8, 0x49, 0xde, 0xcd, 0x95, 0xe4,
	0xa9, 0xb7, 0xd3, 0xde, 0x24, 0xaf, 0x08, 0xb7, 0x37, 0x89, 0x56, 0x62, 0x91, 0x69, 0x71, 0x99,
	0x4a, 0x6f, 0xb7, 0x5d, 0x64, 0x82, 0xb0, 0x5d, 0x84, 0x74, 0xb8, 0x98, 0xa8, 0x4c, 0xa2, 0x0b,
	0xa1, 0xbc, 0x7b, 0xed, 0xc5, 0xbc, 0xd0, 0x84, 0xbd, 0x18, 0xa3, 0x7d, 0xb0, 0x07, 0x9d, 0x13,
	0xa1, 0x6a, 0xe7, 0x58, 0xb3, 0x9c, 0xe3, 0xc1, 0x9f, 0x77, 0x61, 0xd0, 0x3c, 0x69, 0xec, 0x21,
	0x1e, 0xd2, 0x3c, 0x12, 0x69, 0x2a, 0x62, 0x63, 0x41, 0x35, 0xc0, 0x1e, 0x43, 0x6f, 0x96, 0xf2,
	0x85, 0x28, 0xc3, 0x9c, 0x67, 0x68, 0x43, 0xc8, 0x83, 0x86, 0x7e, 0xe1, 0x99, 0x60, 0x7b, 0xe0,
	0x1a, 0x41, 0x12, 0x7b, 0x9d, 0xfd, 0xb5, 0x71, 0x3f, 0x70, 0x34, 0xf0, 0x3a, 0x46, 0x52, 0x09,
	0x9e, 0xe9, 0xd8, 0x75, 0x8a, 0x75, 0x10, 0xa0, 0xc8, 0xfb, 0xb0, 0x49, 0x64, 0x12, 0x7b, 0x5d,
	0x8a, 0xdb, 0xc0, 0xc7, 0xd7, 0x31, 0x63, 0xb0, 0xae, 0x92, 0x4c, 0x78, 0x1b, 0x14, 0x40, 0xbf,
	0xd9, 0x23, 0x80, 0xf3, 0x22, 0x13, 0xc6, 0xb3, 0x36, 0xf7, 0xd7, 0xc6, 0xdd, 0xc0, 0x45, 0x44,
	0x1b, 0xd6, 0x23, 0x00, 0x7e, 0xc9, 0x17, 0x86, 0x76, 0x34, 0x8d, 0x88, 0xa6, 0x31, 0xe3, 0x62,
	0x26, 0xc8, 0x41, 0x30, 0xe3, 0x62, 0x26, 0x26, 0x00, 0x4e, 0x66, 0xda, 0xe7, 0xff, 0x8b, 0x6d,
	0x69, 0xb8, 0x02, 0x9a, 0x73, 0x54, 0x94, 0xb9, 0x28, 0x65, 0x88, 0x79, 0xa8, 0x33, 0xdd, 0xa0,
	0x67, 0xb0, 0xe7, 0x97, 0x7c, 0x61, 0x4b, 0xf0, 0x4d, 0xa8, 0x39, 0xb5, 0xe4, 0xb8, 0xc8, 0x04,
	0xfb, 0x14, 0x06, 0xe8, 0xb4, 0x68, 0x66, 0x26, 0x4f, 0x87, 0x44, 0x5b, 0xa5, 0x88, 0x5f, 0x20,
	0x48, 0x89, 0x1a, 0x2a, 0x4a, 0xb5, 0xde, 0x54, 0x51, 0xae, 0x2f, 0x60, 0x7b, 0x21, 0xd2, 0xb4,
	0xb8, 0xb4, 0xd3, 0x75, 0x49, 0x38, 0xd4, 0x44, 0x9d, 0xb1, 0xad, 0xa5, 0xa4, 0x1b, 0x2b, 0x5a,
	0xca, 0xfb, 0x15, 0xdc, 0x33, 0xda, 0xd6, 0xab, 0xea, 0x2e, 0x33, 0x4d, 0x06, 0xf6, 0x0b, 0x5f,
	0x15, 0x42, 0x25, 0x9c, 0xab, 0x42, 0xb0, 0x8a, 0xff, 0x77, 0x07, 0x46, 0x6d, 0xe3, 0xbd, 0xb2,
	0xc9, 0xee, 0xff, 0x37, 0xd9, 0xbd, 0x49, 0x93, 0xdd, 0x1b, 0x35, 0xd9, 0xbd, 0x69, 0x93, 0xdd,
	0x5b, 0x34, 0xd9, 0xbd, 0x65, 0x93, 0xdd, 0xdb, 0x37, 0xd9, 0xbd, 0xaa, 0xc9, 0xad, 0x53, 0xa2,
	0x77, 0xfb, 0xb5, 0xa7, 0x04, 0x34, 0x5d, 0x9f, 0x92, 0xf6, 0x7d, 0xa4, 0xb7, 0x72, 0x1f, 0xf1,
	0x0f, 0x61, 0xd0, 0x1c, 0x07, 0x98, 0xf3, 0x8c, 0x2f, 0x4b, 0x76, 0xc9, 0x6c, 0x5c, 0x44, 0x28,
	0xa7, 0xbf, 0x0b, 0x6c, 0x75, 0xfc, 0xf9, 0x3b, 0xb0, 0xbd, 0x32, 0xd4, 0x7c, 0x06, 0xa3, 0xf6,
	0xb4, 0xf2, 0xef, 0xc1, 0xce, 0x15, 0x33, 0xc8, 0xff, 0x03, 0x46, 0xed, 0xd1, 0x82, 0x6f, 0x4f,
	0x8b, 0x9b, 0x25, 0x2a, 0x3a, 0x17, 0xa5, 0x69, 0x6c, 0x0f, 0xb1, 0xdf, 0x34, 0x84, 0x12, 0x6a,
	0x4f, 0x25, 0xd1, 0x8d, 0xec, 0x21, 0x66, 0x24, 0xfe, 0x33, 0xf0, 0xae, 0x9b, 0x38, 0xec, 0x23,
	0x80, 0x59, 0x21, 0xa5, 0x90, 0x32, 0x29, 0x72, 0x63, 0x08, 0x16, 0xe2, 0x6f, 0xc3, 0xb0, 0x35,
	0x64, 0xfc, 0xa7, 0xd0, 0x6f, 0x8c, 0x10, 0x74, 0xc4, 0x54, 0x9c, 0x85, 0x95, 0x35, 0x63, 0x0a,
	0x27, 0x15, 0x67, 0xba, 0x59, 0x23, 0x18, 0x34, 0xc7, 0x87, 0x3f, 0x84, 0x7e, 0x63, 0x3a, 0xf8,
	0xff, 0x74, 0x61, 0xd8, 0x32, 0x7f, 0xf6, 0x04, 0x86, 0x71, 0x22, 0xb3, 0x44, 0x4a, 0x9e, 0x36,
	0xdc, 0x6a, 0x50, 0xc3, 0xb4, 0xa3, 0x9a, 0x42, 0xcb, 0xb3, 0x2c, 0x21, 0xed, 0x23, 0x06, 0xeb,
	0xc5, 0x7b, 0x51, 0x1a, 0xb3, 0xa2, 0xdf, 0xcc, 0x83, 0xcd, 0x24, 0xcf, 0x93, 0xfc, 0x4c, 0x1a,
	0x77, 0xaa, 0x1e, 0xf1, 0x1c, 0xcc, 0x44, 0xce, 0x53, 0xb5, 0x08, 0xcb, 0x79, 0x6e, 0x12, 0x1b,
	0x63, 0x32, 0x44, 0x30, 0xcf, 0x97, 0xe7, 0xab, 0xa1, 0xa5, 0xb7, 0xdd, 0x58, 0xd1, 0xd2, 0xeb,
	0xee, 0x01, 0xed, 0x5d, 0x12, 0xd2, 0x66, 0xee, 0x06, 0x0e, 0x02, 0x28, 0x40, 0x92, 0x3e, 0x37,
	0x91, 0xa0, 0x49, 0x04, 0x88, 0xac, 0x3e, 0xf4, 0x25, 0x35, 0x4a, 0xef, 0xe4, 0xae, 0xfe, 0xd0,
	0x6f, 0x35, 0xb4, 0xdc, 0x2e, 0x95, 0x64, 0x4b, 0x4b, 0x10, 0xab, 0x24, 0x38, 0xbd, 0x0a, 0x29,
	0x43, 0x1a, 0x46, 0x78, 0xb3, 0xea, 0x04, 0x0e, 0x02, 0xa7, 0x38, 0x90, 0x9e, 0x02, 0x93, 0x8a,
	0x97, 0x2a, 0x9c, 0x72, 0x85, 0x73, 0x34, 0xc4, 0xe1, 0x45, 0x37, 0xa8, 0x7e, 0x30, 0x22, 0x66,
	0xa2, 0x89, 0x53, 0xc1, 0x33, 0xf6, 0x25, 0xec, 0x46, 0xf3, 0xb2, 0xc4, 0xc3, 0xd5, 0xd0, 0x0f,
	0x49, 0xcf, 0x0c, 0x67, 0x47, 0x3c, 0x86, 0x1e, 0x15, 0xbf, 0x4c, 0xf2, 0x5c, 0x94, 0x74, 0x2f,
	0xea, 0x07, 0x80, 0xd0, 0x5b, 0x42, 0xd8, 0x18, 0x46, 0xb4, 0x46, 0x55, 0x28, 0x9e, 0x86, 0xf8,
	0x89, 0x24, 0x5d, 0x7a, 0xfa, 0xc1, 0x00, 0xf1, 0x53, 0x84, 0x7f, 0x45, 0x14, 0x95, 0xb4, 0x54,
	0x5b, 0xc9, 0xb4, 0x12, 0x71, 0x4b, 0x59, 0x75, 0x9c, 0x3e, 0xfe, 0x8e, 0x1e, 0xe6, 0x08, 0x20,
	0xbb, 0xec, 0x38, 0x91, 0xbb, 0x9a, 0x44, 0x80, 0xc8, 0xca, 0x79, 0xf0, 0xc0, 0x48, 0xba, 0xaf,
	0x18, 0xe7, 0x99, 0x20, 0xb0, 0x74, 0x1e, 0x4d, 0x7f, 0x50, 0x3b, 0x0f, 0xd1, 0x93, 0xcf, 0xe1,
	0x49, 0x54, 0x64, 0x07, 0xd3, 0x44, 0xa1, 0x73, 0xa4, 0x7c, 0x2a, 0x0f, 0xac, 0x7f, 0x52, 0x7c,
	0x96, 0x2c, 0x6f, 0x3e, 0xd3, 0x0d, 0xfa, 0x5f, 0xf5, 0xf5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0x1c, 0x62, 0x55, 0x83, 0x0d, 0x00, 0x00,
}
